import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/components/ClientProvider";
import MenuBar from "@/components/MenuBar";
import Sidebar from "@/components/Sidebar";
import { getCookie } from "cookies-next";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookieStore = cookies();
  const isLoggedIn = cookieStore.get("token")?.value;
  console.log("isLoggedIn:", isLoggedIn);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isLoggedIn ? (
          <ClientProvider>
            <div className="w-full flex h-screen pt-4 box-border">
              <Sidebar />
              <div className="flex flex-col flex-grow pl-12 pr-8">
                <MenuBar />
                <main className="flex-1 p-4">{children}</main>
              </div>
            </div>
          </ClientProvider>
        ) : (
          <main className="flex-1 ">{children}</main>
        )}
        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}
